[package]
name = "websockets"
version = "0.1.0"
authors = ["bakape <scorpid33@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
websocket = "0.19.1"
libc = "0.2.21"
futures = "0.1"
tokio-core = "0.1"
